name: internship_reviewer_app
description: "This project is a mobile application developed using Flutter, designed to help students review and rate their internship experiences. The app allows users to provide feedback on various aspects of their internships, including company environment, mentorship, and skill development."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^7.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
        - asset: lib/assets/fonts/Poppins-Italic.ttf
        - asset: lib/assets/fonts/Poppins-Medium.ttf

  assets:
    - lib/assets/images/logo_internova.png
    - lib/assets/images/splash_screen.png
    - lib/assets/images/logo_google.png
    - lib/assets/images/logo_forgot_password.png
    - lib/assets/images/course_tutor.png
    - lib/assets/images/profile_picture.png
    - lib/assets/images/home_icon.png
    - lib/assets/images/forum_icon.png
    - lib/assets/images/add_icon.png
    - lib/assets/images/qr_scanner_icon.png
    - lib/assets/images/bookmark_icon.png
    - lib/assets/images/logo_shell.png
    - lib/assets/images/logo_bank_negara.png
    - lib/assets/images/logo_petronas.png
    - lib/assets/images/logo_slb.png
    - lib/assets/images/logo_interns.png
    - lib/assets/images/logo_company.png
